ENVIRONMENT:
  DATA_BASE_DIR: '/raid0/myk/Y064/NiiData/'
  CATCH_DIR: '/home/myk/AL_MultiModal/experiment/'

DATA_PREPARE:
  TRAIN_SERIES_IDS_TXT: 'file_list/train_series_uids.txt'
  TEST_SERIES_IDS_TXT: 'file_list/val_series_uids.txt'
  BAD_CASE_SERIES_IDS_TXT: 'file_list/lesion_case.txt'
  #TRAIN_IMAGE_DIR: 'images'
  IMAGE_MODAL: ['CT']
  MASK_MODAL: 'label'
  TRAIN_IMAGE_DIR: 'images'
  TRAIN_MASK_DIR: 'labels'
  TEST_IMAGE_DIR: 'val_images'
  TEST_MASK_DIR: 'val_labels'
  DEFAULT_TRAIN_DB: 'db/seg_pre-process_database'
  DEFAULT_VAL_DB: 'db/seg_pre-process_database'
  OUT_DIR: None
  MASK_LABEL: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  EXTEND_SIZE: 20
  VAL_RATIO: 0.2
  IS_SMOOTH_MASK: False
  IS_NORMALIZATION_DIRECTION: True
  OUT_COARSE_SIZE: [128, 128, 128]
  OUT_FINE_SIZE: [128, 128, 128]
  IS_SPLIT_5FOLD: False
